### ISSUE TITLE
Define environment variables at the project level

### ISSUE THREAD

**Issue by ppcano** [grafana-cold-storage/k6-cloud-feature-requests#71]
### Feature description

Teams organize their testing on various projects. Projects might have different members, scopes, and ways of testing. Projects provide the context for different purposes.

This feature requests to allow configuring [Environment variables](https://k6.io/docs/cloud/manage/notifications/) per project. , which is similar to the request: [Notifications per project](https://github.com/grafana/k6-cloud-feature-requests/issues/42).

Users could create environment variables at either the Stack/organization or project level. The environment variable at the lowest level takes precedence:

- Stack/Organization -->  Project -->  Passing to the CLI 

This is a common pattern in other products such as GitHub.

**Comment by markjmeier** [comment]
This issue has been migrated to Grafana Feature requests (please contact support or your account team to submit additional ideas or to add to this one)
